### ISSUE TITLE
Sorry to bother!

### ISSUE THREAD

**Issue by pakulu** [Frizz925/barawa-bot#1]
Hey there! I saw your autopilot recently because of the "Bistro Feendrache" fiasco.
I am unsure wether you still play or not, but long story short people botted entire sparks by farming this event.
This left me with a very bitter feeling and decided to dig a bit into the bot scene of the game and found your github!
Problem is i have absolutely no idea about coding so even with your instructions i can not make it work. I do think i am very close to it 
![image](https://user-images.githubusercontent.com/44754208/48292532-002f2480-e47b-11e8-9d40-91a211d97964.png)
I think this is the last step towards me getting it to work, not quite sure.
In any case im very sorry for spamming on another one of your proyects but the pilot's issues are closed OTL

**Comment by Frizz925** [comment]
Just quit the game

**Comment by frizz925** [comment]
Please keep the issues on-topic, I do not tolerate intentionally off-topic issues like this one. Closed.
